let categories =
  [

    {
      "id": 518, "image": "https://static.wanted.co.kr/images/tags/675ed3b6.jpg",
      "tags": [
        { "id": 872, "image": "https://static.wanted.co.kr/images/tags/468d23ec-43fa-11e6-90dd-0a30d591bfc5.jpg", "title": "서버 개발자", "counts": { "job": 1620, "externalJob": 14924 }, "tagName": "back-end engineer" },
        { "id": 873, "image": "https://static.wanted.co.kr/images/tags/512ec544-43fa-11e6-90dd-0a30d591bfc5.jpg", "title": "웹 개발자", "counts": { "job": 1562, "externalJob": 80292 }, "tagName": "web developer" },
        { "id": 669, "image": "https://static.wanted.co.kr/images/tags/55d008e2-43fa-11e6-90dd-0a30d591bfc5.jpg", "title": "프론트엔드 개발자", "counts": { "job": 1340, "externalJob": 17105 }, "tagName": "front-end engineer" },
        { "id": 660, "image": "https://static.wanted.co.kr/images/tags/773638bc-43fa-11e6-945a-0a30d591bfc5.jpg", "title": "자바 개발자", "counts": { "job": 1076, "externalJob": 47843 }, "tagName": "java developer" },
        { "id": 10110, "image": "https://static.wanted.co.kr/images/tags/9e2b6c64.jpg", "title": "소프트웨어 엔지니어", "counts": { "job": 1013, "externalJob": 6494 }, "tagName": "software engineer" },
        { "id": 677, "image": "https://static.wanted.co.kr/images/tags/63b50034-43fa-11e6-aa6b-0a30d591bfc5.jpg", "title": "안드로이드 개발자", "counts": { "job": 582, "externalJob": 5412 }, "tagName": "android developer" },
        { "id": 678, "image": "https://static.wanted.co.kr/images/tags/0c9e1334-43fb-11e6-aa6b-0a30d591bfc5.jpg", "title": "iOS 개발자", "counts": { "job": 545, "externalJob": 10202 }, "tagName": "ios developer" },
        { "id": 655, "image": "https://static.wanted.co.kr/images/tags/92c96586-43fa-11e6-aa6b-0a30d591bfc5.jpg", "title": "데이터 엔지니어", "counts": { "job": 483, "externalJob": 54208 }, "tagName": "data engineer" },
        { "id": 899, "image": "https://static.wanted.co.kr/images/tags/c9f29c76-43fa-11e6-90dd-0a30d591bfc5.jpg", "title": "파이썬 개발자", "counts": { "job": 472, "externalJob": 25961 }, "tagName": "python developer" },
        { "id": 674, "image": "https://static.wanted.co.kr/images/tags/9b6c1db4-43fa-11e6-b947-0a30d591bfc5.jpg", "title": "DevOps / 시스템 관리자", "counts": { "job": 418, "externalJob": 32200 }, "tagName": "devops or system admin" },
        { "id": 895, "image": "https://static.wanted.co.kr/images/tags/ddb56fa4-43fa-11e6-90dd-0a30d591bfc5.jpg", "title": "Node.js 개발자", "counts": { "job": 414, "externalJob": 7912 }, "tagName": "node.js developer" },
        { "id": 665, "image": "https://static.wanted.co.kr/images/tags/b6181050-43fa-11e6-945a-0a30d591bfc5.jpg", "title": "시스템,네트워크 관리자", "counts": { "job": 390, "externalJob": 107204 }, "tagName": "system, network administrator" },
        { "id": 900, "image": "https://static.wanted.co.kr/images/tags/ac80b132-43fa-11e6-80ef-0a30d591bfc5.jpg", "title": "C,C++ 개발자", "counts": { "job": 372, "externalJob": 40890 }, "tagName": "c,c++ developer" },
        { "id": 1634, "image": "https://static.wanted.co.kr/images/tags/ebfb705e.jpg", "title": "머신러닝 엔지니어", "counts": { "job": 340, "externalJob": 26903 }, "tagName": "machine learning engineer" },
        { "id": 1024, "image": "https://static.wanted.co.kr/images/tags/d7c9679e.jpg", "title": "데이터 사이언티스트", "counts": { "job": 323, "externalJob": 11365 }, "tagName": "data scientist" },
        { "id": 877, "image": "https://static.wanted.co.kr/images/tags/881cf3aa-43fa-11e6-945a-0a30d591bfc5.jpg", "title": "개발 매니저", "counts": { "job": 276, "externalJob": 80831 }, "tagName": "development manager" },
        { "id": 1025, "image": "https://static.wanted.co.kr/images/tags/6b6111e6.jpg", "title": "빅데이터 엔지니어", "counts": { "job": 268, "externalJob": 13392 }, "tagName": "big data engineer" },
        { "id": 676, "image": "https://static.wanted.co.kr/images/tags/385b71ec-43fb-11e6-90dd-0a30d591bfc5.jpg", "title": "QA,테스트 엔지니어", "counts": { "job": 232, "externalJob": 22229 }, "tagName": "qa, test engineer" },
        { "id": 1026, "image": "https://static.wanted.co.kr/images/tags/0ad4c3f8.jpg", "title": "기술지원", "counts": { "job": 205, "externalJob": 111732 }, "tagName": "technical support" },
        { "id": 671, "image": "https://static.wanted.co.kr/images/tags/fa0832d6-43fa-11e6-b947-0a30d591bfc5.jpg", "title": "보안 엔지니어", "counts": { "job": 179, "externalJob": 41469 }, "tagName": "security engineer" },
        { "id": 893, "image": "https://static.wanted.co.kr/images/tags/e52b0f50-43fa-11e6-90dd-0a30d591bfc5.jpg", "title": "PHP 개발자", "counts": { "job": 162, "externalJob": 30511 }, "tagName": "php developer" },
        { "id": 876, "image": "https://static.wanted.co.kr/images/tags/ff75299a-43fa-11e6-945a-0a30d591bfc5.jpg", "title": "프로덕트 매니저", "counts": { "job": 144, "externalJob": 40823 }, "tagName": "product manager" },
        { "id": 939, "image": "https://static.wanted.co.kr/images/tags/f4b038fa-902c-11e6-ac23-0a30d591bfc5.png", "title": "웹 퍼블리셔", "counts": { "job": 127, "externalJob": 1342 }, "tagName": "web publisher" },
        { "id": 658, "image": "https://static.wanted.co.kr/images/tags/47046ea6-43fb-11e6-90dd-0a30d591bfc5.jpg", "title": "임베디드 개발자", "counts": { "job": 95, "externalJob": 23002 }, "tagName": "embedded developer" },
        { "id": 1027, "image": "https://static.wanted.co.kr/images/tags/ed3d7974.jpg", "title": "블록체인 플랫폼 엔지니어", "counts": { "job": 95, "externalJob": 1419 }, "tagName": "blockchain platform engineer" },
        { "id": 661, "image": "https://static.wanted.co.kr/images/tags/8000714c-43fa-11e6-80ef-0a30d591bfc5.jpg", "title": ".NET 개발자", "counts": { "job": 77, "externalJob": 45056 }, "tagName": ".net developer" },
        { "id": 10111, "image": "https://static.wanted.co.kr/images/tags/5cb28ea5.jpg", "title": "크로스플랫폼 앱 개발자", "counts": { "job": 77, "externalJob": 17 }, "tagName": "cross-platform app developer" },
        { "id": 672, "image": "https://static.wanted.co.kr/images/tags/082e8a54-0318-11e7-8094-0213e6175ee7.jpg", "title": "하드웨어 엔지니어", "counts": { "job": 75, "externalJob": 22233 }, "tagName": "hardware engineer" },
        { "id": 896, "image": "https://static.wanted.co.kr/images/tags/9839253a-43e9-11e6-90dd-0a30d591bfc5.jpg", "title": "영상,음성 엔지니어", "counts": { "job": 58, "externalJob": 14779 }, "tagName": "video, voice engineer" },
        { "id": 795, "image": "https://static.wanted.co.kr/images/tags/f3c39c8a-43fa-11e6-945a-0a30d591bfc5.jpg", "title": "CTO,Chief Technology Officer", "counts": { "job": 44, "externalJob": 6573 }, "tagName": "cto,chief technology officer" },
        { "id": 898, "image": "https://static.wanted.co.kr/images/tags/ee2e96da-43fa-11e6-80ef-0a30d591bfc5.jpg", "title": "그래픽스 엔지니어", "counts": { "job": 38, "externalJob": 1698 }, "tagName": "graphics engineer" },
        { "id": 894, "image": "https://static.wanted.co.kr/images/tags/d06f06b6-43fa-11e6-945a-0a30d591bfc5.jpg", "title": "루비온레일즈 개발자", "counts": { "job": 34, "externalJob": 7076 }, "tagName": "ruby on rails developer" },
        { "id": 1022, "image": "https://static.wanted.co.kr/images/tags/7346b754.jpg", "title": "BI 엔지니어", "counts": { "job": 32, "externalJob": 6406 }, "tagName": "bi engineer" },
        { "id": 10112, "image": "https://static.wanted.co.kr/images/tags/af0691aa.jpg", "title": "VR 엔지니어", "counts": { "job": 27, "externalJob": 256 }, "tagName": "vr engineer" },
        { "id": 793, "image": "https://static.wanted.co.kr/images/tags/d0cce80e-4282-11e6-adae-029e8c03f357.jpg", "title": "CIO,Chief Information Officer", "counts": { "job": 5, "externalJob": 3975 }, "tagName": "cio,chief information officer" }],
      "title": "개발",
      "counts": { "job": 6273, "externalJob": 0 },
      "tagName": "it"
    },
    {
      "id": 507, "image": "https://static.wanted.co.kr/images/tags/a5cfdc9e.jpg",
      "tags": [
        { "id": 565, "image": "https://static.wanted.co.kr/images/tags/64320d72-43eb-11e6-90dd-0a30d591bfc5.jpg", "title": "서비스 기획자", "counts": { "job": 963, "externalJob": 69961 }, "tagName": "service planner" },
        { "id": 564, "image": "https://static.wanted.co.kr/images/tags/734d1fe4-43e2-11e6-90dd-0a30d591bfc5.jpg", "title": "사업개발·기획자", "counts": { "job": 868, "externalJob": 123400 }, "tagName": "business development" },
        { "id": 559, "image": "https://static.wanted.co.kr/images/tags/c1a668d0-4289-11e6-870e-029e8c03f357.jpg", "title": "PM·PO", "counts": { "job": 836, "externalJob": 79173 }, "tagName": "project manager" },
        { "id": 563, "image": "https://static.wanted.co.kr/images/tags/66a5754c-43e3-11e6-945a-0a30d591bfc5.jpg", "title": "전략 기획자", "counts": { "job": 536, "externalJob": 12113 }, "tagName": "strategic planner" },
        { "id": 554, "image": "https://static.wanted.co.kr/images/tags/7e2cb988-43e2-11e6-b947-0a30d591bfc5.jpg", "title": "운영 매니저", "counts": { "job": 338, "externalJob": 99886 }, "tagName": "operations manager" },
        { "id": 552, "image": "https://static.wanted.co.kr/images/tags/6340bbb0-43e2-11e6-90dd-0a30d591bfc5.jpg", "title": "경영지원", "counts": { "job": 304, "externalJob": 85956 }, "tagName": "business support manager" },
        { "id": 656, "image": "https://static.wanted.co.kr/images/tags/6d972c2a-43e2-11e6-aa6b-0a30d591bfc5.jpg", "title": "데이터 분석가", "counts": { "job": 257, "externalJob": 37719 }, "tagName": "data analyst" },
        { "id": 1034, "image": "https://static.wanted.co.kr/images/tags/2ae0d434.jpg", "title": "회계·경리", "counts": { "job": 202, "externalJob": 107291 }, "tagName": "accountant" },
        { "id": 562, "image": "https://static.wanted.co.kr/images/tags/edbd386e-0254-11e7-b0b5-0219382c3fab.jpg", "title": "총무", "counts": { "job": 130, "externalJob": 99853 }, "tagName": "general affairs" },
        { "id": 10115, "image": "https://static.wanted.co.kr/images/tags/7ce8d9c3.jpg", "title": "해외 사업개발·기획자", "counts": { "job": 109, "externalJob": 858 }, "tagName": "global business development manager" },
        { "id": 10116, "image": "https://static.wanted.co.kr/images/tags/f1022cac.jpg", "title": "자금담당", "counts": { "job": 100, "externalJob": 3114 }, "tagName": "finance manager" },
        { "id": 570, "image": "https://static.wanted.co.kr/images/tags/329c437e-0315-11e7-8094-0213e6175ee7.jpg", "title": "컨설턴트", "counts": { "job": 99, "externalJob": 112602 }, "tagName": "consultant" },
        { "id": 567, "image": "https://static.wanted.co.kr/images/tags/a99c6ef0-4fcd-11e6-852d-0a30d591bfc5.jpg", "title": "조직관리", "counts": { "job": 61, "externalJob": 87968 }, "tagName": "organization management" },
        { "id": 557, "image": "https://static.wanted.co.kr/images/tags/02902182-4fce-11e6-844a-0a30d591bfc5.jpg", "title": "오피스 관리", "counts": { "job": 49, "externalJob": 40196 }, "tagName": "office manager" },
        { "id": 10122, "image": "https://static.wanted.co.kr/images/tags/3170d28f.jpg", "title": "사무보조", "counts": { "job": 35, "externalJob": 3177 }, "tagName": "administrative assistant" },
        { "id": 561, "image": "https://static.wanted.co.kr/images/tags/b3857dd2.jpg", "title": "구매담당", "counts": { "job": 33, "externalJob": 21733 }, "tagName": "purchasing manager" },
        { "id": 568, "image": "https://static.wanted.co.kr/images/tags/691e7b76-43e2-11e6-945a-0a30d591bfc5.jpg", "title": "경영 혁신가", "counts": { "job": 33, "externalJob": 1233 }, "tagName": "management innovator" },
        { "id": 569, "image": "https://static.wanted.co.kr/images/tags/b83760a4-0257-11e7-b0b5-0219382c3fab.jpg", "title": "리스크 관리 전문가", "counts": { "job": 31, "externalJob": 26402 }, "tagName": "risk management specialist" },
        { "id": 558, "image": "https://static.wanted.co.kr/images/tags/79e6764c-43e3-11e6-945a-0a30d591bfc5.jpg", "title": "지역 관리 매니저", "counts": { "job": 24, "externalJob": 57338 }, "tagName": "local manager" },
        { "id": 550, "image": "https://static.wanted.co.kr/images/tags/f0e9849c.jpg", "title": "비서", "counts": { "job": 19, "externalJob": 26123 }, "tagName": "secretary" },
        { "id": 792, "image": "https://static.wanted.co.kr/images/tags/8ccf65da-43e2-11e6-90dd-0a30d591bfc5.jpg", "title": "CFO,Chief Financial Officer", "counts": { "job": 17, "externalJob": 6260 }, "tagName": "cfo,chief financial officer" },
        { "id": 794, "image": "https://static.wanted.co.kr/images/tags/922f8bd6-43e2-11e6-90dd-0a30d591bfc5.jpg", "title": "COO,Chief Operation Officer", "counts": { "job": 12, "externalJob": 4943 }, "tagName": "coo,chief operation officer" },
        { "id": 798, "image": "https://static.wanted.co.kr/images/tags/9708ef26-43e2-11e6-aa6b-0a30d591bfc5.jpg", "title": "CSO,Chief Strategy Officer", "counts": { "job": 9, "externalJob": 3279 }, "tagName": "cso,chief strategy officer" },
        { "id": 10120, "image": "https://static.wanted.co.kr/images/tags/50791e1b.jpg", "title": "애자일코치", "counts": { "job": 6, "externalJob": 61 }, "tagName": "agile coach" },
        { "id": 10118, "image": "https://static.wanted.co.kr/images/tags/096c4282.jpg", "title": "세미나/포럼 기획자", "counts": { "job": 5, "externalJob": 14 }, "tagName": "event producer" },
        { "id": 10119, "image": "https://static.wanted.co.kr/images/tags/1055d9b3.jpg", "title": "공연 기획자", "counts": { "job": 4, "externalJob": 14 }, "tagName": "stage producer" },
        { "id": 560, "image": "https://static.wanted.co.kr/images/tags/8a0aa216-0254-11e7-8ad5-0219382c3fab.jpg", "title": "지점장", "counts": { "job": 3, "externalJob": 23314 }, "tagName": "branch manager" },
        { "id": 791, "image": "https://static.wanted.co.kr/images/tags/8824dda8-43e2-11e6-90dd-0a30d591bfc5.jpg", "title": "CEO,Chief Executive Officer", "counts": { "job": 3, "externalJob": 13038 }, "tagName": "ceo,chief executive officer" },
        { "id": 10117, "image": "https://static.wanted.co.kr/images/tags/f9eff092.jpg", "title": "전시 기획자", "counts": { "job": 3, "externalJob": 183 }, "tagName": "exhibition planner" },
        { "id": 10121, "image": "https://static.wanted.co.kr/images/tags/b7d6a026.jpg", "title": "사내 심리상담가", "counts": { "job": 2, "externalJob": 15 }, "tagName": "eap counselor" },
        { "id": 555, "image": "https://static.wanted.co.kr/images/tags/7250c300.jpg", "title": "안내원", "counts": { "job": 1, "externalJob": 81011 }, "tagName": "guide" }],
      "title": "경영·비즈니스", "counts": { "job": 2308, "externalJob": 0 }, "tagName": "management and business"
    },

    {
      "id": 523, "image": "https://static.wanted.co.kr/images/tags/4a95ff52.jpg",
      "tags": [
        { "id": 710, "image": "https://static.wanted.co.kr/images/tags/4198a60e-43eb-11e6-90dd-0a30d591bfc5.jpg", "title": "마케터", "counts": { "job": 746, "externalJob": 16011 }, "tagName": "marketer" },
        { "id": 1030, "image": "https://static.wanted.co.kr/images/tags/562aab1c.jpg", "title": "디지털 마케터", "counts": { "job": 642, "externalJob": 19497 }, "tagName": "digital marketer" },
        { "id": 10138, "image": "https://static.wanted.co.kr/images/tags/45f471b6.jpg", "title": "퍼포먼스 마케터", "counts": { "job": 528, "externalJob": 866 }, "tagName": "performance marketing manager" },
        { "id": 1635, "image": "https://static.wanted.co.kr/images/tags/e46fa238.jpg", "title": "콘텐츠 마케터", "counts": { "job": 501, "externalJob": 7726 }, "tagName": "content marketer" },
        { "id": 719, "image": "https://static.wanted.co.kr/images/tags/47aad33c-43eb-11e6-80ef-0a30d591bfc5.jpg", "title": "마케팅 전략 기획자", "counts": { "job": 376, "externalJob": 7984 }, "tagName": "marketing strategy planner" },
        { "id": 707, "image": "https://static.wanted.co.kr/images/tags/52e45912-43eb-11e6-90dd-0a30d591bfc5.jpg", "title": "브랜드 마케터", "counts": { "job": 341, "externalJob": 16709 }, "tagName": "brand marketer" },
        { "id": 763, "image": "https://static.wanted.co.kr/images/tags/b702e312-43f7-11e6-90dd-0a30d591bfc5.jpg", "title": "광고 기획자(AE)", "counts": { "job": 176, "externalJob": 15312 }, "tagName": "account executive" },
        { "id": 721, "image": "https://static.wanted.co.kr/images/tags/afe92e26-43eb-11e6-90dd-0a30d591bfc5.jpg", "title": "소셜 마케터", "counts": { "job": 163, "externalJob": 4989 }, "tagName": "social marketer" },
        { "id": 950, "image": "https://static.wanted.co.kr/images/tags/b991785c-ccbc-11e6-b4e9-0a30d591bfc5.jpg", "title": "글로벌 마케팅", "counts": { "job": 150, "externalJob": 23699 }, "tagName": "global marketing mgr." },
        { "id": 717, "image": "https://static.wanted.co.kr/images/tags/3af6d230-43eb-11e6-90dd-0a30d591bfc5.jpg", "title": "그로스 해커", "counts": { "job": 142, "externalJob": 108 }, "tagName": "growth hacker" },
        { "id": 714, "image": "https://static.wanted.co.kr/images/tags/a9af67d2-43eb-11e6-90dd-0a30d591bfc5.jpg", "title": "PR 전문가", "counts": { "job": 104, "externalJob": 39882 }, "tagName": "pr specialist" },
        { "id": 1033, "image": "https://static.wanted.co.kr/images/tags/ffa906e8.jpg", "title": "모바일마케팅", "counts": { "job": 89, "externalJob": 1184 }, "tagName": "mobile marketing specialist" },
        { "id": 1032, "image": "https://static.wanted.co.kr/images/tags/b822bf9e.jpg", "title": "마케팅 디렉터", "counts": { "job": 71, "externalJob": 16895 }, "tagName": "marketing director" },
        { "id": 708, "image": "https://static.wanted.co.kr/images/tags/877473f6-43eb-11e6-80ef-0a30d591bfc5.jpg", "title": "카피라이터", "counts": { "job": 63, "externalJob": 3313 }, "tagName": "copywriter" },
        { "id": 720, "image": "https://static.wanted.co.kr/images/tags/9ad988d0-428a-11e6-870e-029e8c03f357.jpg", "title": "제휴", "counts": { "job": 53, "externalJob": 2935 }, "tagName": "partnership specialist" },
        { "id": 722, "image": "https://static.wanted.co.kr/images/tags/8d86465c-43eb-11e6-aa6b-0a30d591bfc5.jpg", "title": "키워드광고", "counts": { "job": 52, "externalJob": 9217 }, "tagName": "seo marketing manager" },
        { "id": 709, "image": "https://static.wanted.co.kr/images/tags/4dde7fc4-43eb-11e6-90dd-0a30d591bfc5.jpg", "title": "마켓 리서처", "counts": { "job": 37, "externalJob": 1174 }, "tagName": "market researcher" },
        { "id": 799, "image": "https://static.wanted.co.kr/images/tags/a3efa19a-43eb-11e6-80ef-0a30d591bfc5.jpg", "title": "CMO,Chief Marketing Officer", "counts": { "job": 20, "externalJob": 2101 }, "tagName": "cmo,chief marketing officer" },
        { "id": 716, "image": "https://static.wanted.co.kr/images/tags/9c71cc9a-43eb-11e6-945a-0a30d591bfc5.jpg", "title": "BTL 마케터", "counts": { "job": 13, "externalJob": 67 }, "tagName": "btl marketer" },
        { "id": 715, "image": "https://static.wanted.co.kr/images/tags/9557eae8-43eb-11e6-90dd-0a30d591bfc5.jpg", "title": "ATL 마케터", "counts": { "job": 12, "externalJob": 53 }, "tagName": "atl marketer" },
        { "id": 801, "image": "https://static.wanted.co.kr/images/tags/906eab12-4282-11e6-adae-029e8c03f357.jpg", "title": "CBO,Chief Brand Officer", "counts": { "job": 5, "externalJob": 635 }, "tagName": "cbo,chief brand officer" },
        { "id": 1031, "image": "https://static.wanted.co.kr/images/tags/a9a5dc62.jpg", "title": "Sports 전문가", "counts": { "job": 2, "externalJob": 569 }, "tagName": "sports specialist" }],
      "title": "마케팅·광고", "counts": { "job": 1699, "externalJob": 0 }, "tagName": "marketing and advertising"
    },

    {
      "id": 511, "image": "https://static.wanted.co.kr/images/tags/8d39d3a6.jpg", "tags": [
        { "id": 599, "image": "https://static.wanted.co.kr/images/tags/c5ec179e-43e9-11e6-90dd-0a30d591bfc5.jpg", "title": "UX 디자이너", "counts": { "job": 726, "externalJob": 17708 }, "tagName": "ux designer" },
        { "id": 597, "image": "https://static.wanted.co.kr/images/tags/c08d07d6-43e9-11e6-aa6b-0a30d591bfc5.jpg", "title": "UI,GUI 디자이너", "counts": { "job": 662, "externalJob": 26162 }, "tagName": "ui,gui designer" },
        { "id": 594, "image": "https://static.wanted.co.kr/images/tags/9d0bbe4c-43e9-11e6-90dd-0a30d591bfc5.jpg", "title": "웹 디자이너", "counts": { "job": 537, "externalJob": 46774 }, "tagName": "web designer" },
        { "id": 592, "image": "https://static.wanted.co.kr/images/tags/8108a67e-43e9-11e6-90dd-0a30d591bfc5.jpg", "title": "그래픽 디자이너", "counts": { "job": 341, "externalJob": 18171 }, "tagName": "graphic designer" },
        { "id": 595, "image": "https://static.wanted.co.kr/images/tags/8644c992-43e9-11e6-90dd-0a30d591bfc5.jpg", "title": "모바일 디자이너", "counts": { "job": 260, "externalJob": 12705 }, "tagName": "mobile designer" },
        { "id": 1029, "image": "https://static.wanted.co.kr/images/tags/cc1c36e0.jpg", "title": "광고 디자이너", "counts": { "job": 172, "externalJob": 27755 }, "tagName": "ad designer" },
        { "id": 879, "image": "https://static.wanted.co.kr/images/tags/bc84a270-43e9-11e6-90dd-0a30d591bfc5.jpg", "title": "BI/BX 디자이너", "counts": { "job": 165, "externalJob": 2130 }, "tagName": "bi or bx designer" },
        { "id": 602, "image": "https://static.wanted.co.kr/images/tags/8edaa342-43e9-11e6-80ef-0a30d591bfc5.jpg", "title": "영상,모션 디자이너", "counts": { "job": 120, "externalJob": 16377 }, "tagName": "video, motion designer" },
        { "id": 603, "image": "https://static.wanted.co.kr/images/tags/b76b9f82-43e9-11e6-945a-0a30d591bfc5.jpg", "title": "제품 디자이너", "counts": { "job": 108, "externalJob": 32297 }, "tagName": "product designer" },
        { "id": 929, "image": "https://static.wanted.co.kr/images/tags/a1784abe-4fc3-11e6-852d-0a30d591bfc5.jpg", "title": "3D 디자이너", "counts": { "job": 104, "externalJob": 8046 }, "tagName": "3d designer" },
        { "id": 593, "image": "https://static.wanted.co.kr/images/tags/8a7fe870-43e9-11e6-90dd-0a30d591bfc5.jpg", "title": "아트 디렉터", "counts": { "job": 66, "externalJob": 5386 }, "tagName": "art director" },
        { "id": 596, "image": "https://static.wanted.co.kr/images/tags/b3119ea0-43e9-11e6-90dd-0a30d591bfc5.jpg", "title": "일러스트레이터", "counts": { "job": 61, "externalJob": 23834 }, "tagName": "illustrator" },
        { "id": 928, "image": "https://static.wanted.co.kr/images/tags/516ced3e-637f-11e6-831d-0a30d591bfc5.jpg", "title": "2D 디자이너", "counts": { "job": 59, "externalJob": 3042 }, "tagName": "2d designer" },
        { "id": 10130, "image": "https://static.wanted.co.kr/images/tags/a897260c.jpg", "title": "패키지 디자이너", "counts": { "job": 58, "externalJob": 834 }, "tagName": "packaging designer" },
        { "id": 951, "image": "https://static.wanted.co.kr/images/tags/c3503360-ccbc-11e6-84e1-0a30d591bfc5.jpg", "title": "캐릭터 디자이너", "counts": { "job": 48, "externalJob": 6343 }, "tagName": "character designer" },
        { "id": 606, "image": "https://static.wanted.co.kr/images/tags/7bb4eab6-43e9-11e6-90dd-0a30d591bfc5.jpg", "title": "공간 디자이너", "counts": { "job": 26, "externalJob": 17216 }, "tagName": "space designer" },
        { "id": 952, "image": "https://static.wanted.co.kr/images/tags/ccf551f2-ccbc-11e6-95de-0a30d591bfc5.jpg", "title": "출판, 편집 디자이너", "counts": { "job": 26, "externalJob": 5497 }, "tagName": "editorial designer" },
        { "id": 601, "image": "https://static.wanted.co.kr/images/tags/a2574dc6-43e9-11e6-80ef-0a30d591bfc5.jpg", "title": "인테리어 디자이너", "counts": { "job": 23, "externalJob": 26916 }, "tagName": "interior designer" },
        { "id": 953, "image": "https://static.wanted.co.kr/images/tags/d5c8b328-ccbc-11e6-84e1-0a30d591bfc5.jpg", "title": "패션 디자이너", "counts": { "job": 21, "externalJob": 18079 }, "tagName": "fashion designer" },
        { "id": 600, "image": "https://static.wanted.co.kr/images/tags/611b7e9e-637f-11e6-831d-0a30d591bfc5.jpg", "title": "산업 디자이너", "counts": { "job": 18, "externalJob": 12898 }, "tagName": "industrial designer" },
        { "id": 10128, "image": "https://static.wanted.co.kr/images/tags/5109ee46.jpg", "title": "패브릭 디자이너", "counts": { "job": 8, "externalJob": 27 }, "tagName": "textile designer" },
        { "id": 10131, "image": "https://static.wanted.co.kr/images/tags/4be65f25.jpg", "title": "VMD", "counts": { "job": 6, "externalJob": 91 }, "tagName": "vmd designer" },
        { "id": 10129, "image": "https://static.wanted.co.kr/images/tags/974fce01.jpg", "title": "전시 디자이너", "counts": { "job": 5, "externalJob": 162 }, "tagName": "exhibition designer" },
        { "id": 10127, "image": "https://static.wanted.co.kr/images/tags/999a9a57.jpg", "title": "가구 디자이너", "counts": { "job": 3, "externalJob": 971 }, "tagName": "furniture designer" },
        { "id": 605, "image": "https://static.wanted.co.kr/images/tags/0f9eaedc.jpg", "title": "조경 디자이너", "counts": { "job": 2, "externalJob": 15905 }, "tagName": "landscape designer" }],
      "title": "디자인", "counts": { "job": 1495, "externalJob": 0 }, "tagName": "design"
    },

    {
      "id": 510, "image": "https://static.wanted.co.kr/images/tags/9242fbde.jpg", "tags": [
        { "id": 758, "image": "https://static.wanted.co.kr/images/tags/07b18d3c-4726-11e6-b9ca-0a30d591bfc5.jpg", "title": "MD", "counts": { "job": 318, "externalJob": 11027 }, "tagName": "merchandiser" },
        { "id": 10126, "image": "https://static.wanted.co.kr/images/tags/1028a03b.jpg", "title": "서비스 운영", "counts": { "job": 286, "externalJob": 2720 }, "tagName": "customer service representative" },
        { "id": 1028, "image": "https://static.wanted.co.kr/images/tags/dc946f10.jpg", "title": "CS 매니저", "counts": { "job": 276, "externalJob": 30275 }, "tagName": "customer service manager" },
        { "id": 760, "image": "https://static.wanted.co.kr/images/tags/ed0fbc08-4fc5-11e6-be31-0a30d591bfc5.jpg", "title": "리테일 MD", "counts": { "job": 158, "externalJob": 824 }, "tagName": "retail merchandiser" },
        { "id": 586, "image": "https://static.wanted.co.kr/images/tags/d8f6a8fe-43e4-11e6-90dd-0a30d591bfc5.jpg", "title": "CS 어드바이저", "counts": { "job": 157, "externalJob": 41805 }, "tagName": "cs advisor" },
        { "id": 759, "image": "https://static.wanted.co.kr/images/tags/3fa49738-43e4-11e6-90dd-0a30d591bfc5.jpg", "title": "패션 MD", "counts": { "job": 103, "externalJob": 4013 }, "tagName": "fashion merchandiser" },
        { "id": 901, "image": "https://static.wanted.co.kr/images/tags/e8af3a40-43e4-11e6-90dd-0a30d591bfc5.jpg", "title": "CRM 전문가", "counts": { "job": 75, "externalJob": 10637 }, "tagName": "crm specialist" },
        { "id": 752, "image": "https://static.wanted.co.kr/images/tags/7a0d5b08-03a1-11e7-8ad5-0219382c3fab.jpg", "title": "매장 관리자", "counts": { "job": 34, "externalJob": 49557 }, "tagName": "store manager" },
        { "id": 769, "image": "https://static.wanted.co.kr/images/tags/201efdc4-ccbd-11e6-84e1-0a30d591bfc5.jpg", "title": "인바운드 텔레마케터", "counts": { "job": 31, "externalJob": 8956 }, "tagName": "inbound telemarketer" },
        { "id": 639, "image": "https://static.wanted.co.kr/images/tags/aa115ff6.jpg", "title": "이벤트 기획자", "counts": { "job": 17, "externalJob": 16741 }, "tagName": "event planner" },
        { "id": 762, "image": "https://static.wanted.co.kr/images/tags/7f65e6aa-03a7-11e7-8ad5-0219382c3fab.jpg", "title": "가맹점 관리자", "counts": { "job": 17, "externalJob": 1583 }, "tagName": "franchise manager" },
        { "id": 754, "image": "https://static.wanted.co.kr/images/tags/86eaba14-03a1-11e7-a97f-0213e6175ee7.jpg", "title": "매장점원", "counts": { "job": 15, "externalJob": 76513 }, "tagName": "retail salesperson" },
        { "id": 902, "image": "https://static.wanted.co.kr/images/tags/16f65c24-ccbd-11e6-b4e9-0a30d591bfc5.jpg", "title": "아웃바운드 텔레마케터", "counts": { "job": 10, "externalJob": 5796 }, "tagName": "outbound telemarketer" },
        { "id": 757, "image": "https://static.wanted.co.kr/images/tags/5ec37a3a-03a6-11e7-a894-0aba6235ef6f.jpg", "title": "비주얼머천다이저", "counts": { "job": 7, "externalJob": 2702 }, "tagName": "visual merchandiser" },
        { "id": 1637, "image": "https://static.wanted.co.kr/images/tags/003c9f64.jpg", "title": "헬스케어매니저", "counts": { "job": 6, "externalJob": 17642 }, "tagName": "healthcare manager" },
        { "id": 641, "image": "https://static.wanted.co.kr/images/tags/a84979c0.jpg", "title": "여행 에이전트", "counts": { "job": 5, "externalJob": 77129 }, "tagName": "travel agent" },
        { "id": 10125, "image": "https://static.wanted.co.kr/images/tags/63fead51.jpg", "title": "리셉션", "counts": { "job": 5, "externalJob": 1088 }, "tagName": "receptionist" },
        { "id": 591, "image": "https://static.wanted.co.kr/images/tags/0569f716.jpg", "title": "AS 기술자", "counts": { "job": 4, "externalJob": 52454 }, "tagName": "service technician" },
        { "id": 755, "image": "https://static.wanted.co.kr/images/tags/966b5ec4.jpg", "title": "피부관리사", "counts": { "job": 1, "externalJob": 44369 }, "tagName": "esthetician" },
        { "id": 589, "image": "https://static.wanted.co.kr/images/tags/40e3edb0.jpg", "title": "승무원", "counts": { "job": 0, "externalJob": 9209 }, "tagName": "flight attendant" },
        { "id": 640, "image": "https://static.wanted.co.kr/images/tags/af4994a6.jpg", "title": "플로리스트", "counts": { "job": 0, "externalJob": 2611 }, "tagName": "florist" },
        { "id": 756, "image": "https://static.wanted.co.kr/images/tags/c79cefbc.jpg", "title": "헤어 디자이너", "counts": { "job": 0, "externalJob": 15092 }, "tagName": "hair designer" },
        { "id": 10123, "image": "https://static.wanted.co.kr/images/tags/ae9f700e.jpg", "title": "미용사", "counts": { "job": 0, "externalJob": 1832 }, "tagName": "hairdresser" },
        { "id": 10124, "image": "https://static.wanted.co.kr/images/tags/30e57a62.jpg", "title": "애견 미용사", "counts": { "job": 0, "externalJob": 470 }, "tagName": "pet stylist" }],
      "title": "고객서비스·리테일", "counts": { "job": 693, "externalJob": 0 }, "tagName": "customer service"
    },
    {
      "id": 530, "image": "https://static.wanted.co.kr/images/tags/3c36ce46.jpg",
      "tags": [
        { "id": 1036, "image": "https://static.wanted.co.kr/images/tags/b76d0598.jpg", "title": "기업영업", "counts": { "job": 333, "externalJob": 19905 }, "tagName": "enterprise sales" },
        { "id": 766, "image": "https://static.wanted.co.kr/images/tags/b1863c0e-43f7-11e6-90dd-0a30d591bfc5.jpg", "title": "외부영업", "counts": { "job": 285, "externalJob": 71508 }, "tagName": "sales specialist" },
        { "id": 954, "image": "https://static.wanted.co.kr/images/tags/dfea25ee-ccbc-11e6-84e1-0a30d591bfc5.jpg", "title": "영업 관리자", "counts": { "job": 245, "externalJob": 58536 }, "tagName": "sales team lead" },
        { "id": 768, "image": "https://static.wanted.co.kr/images/tags/c7b628c0-03a7-11e7-8094-0213e6175ee7.jpg", "title": "주요고객사 담당자", "counts": { "job": 180, "externalJob": 22265 }, "tagName": "account manager" },
        { "id": 770, "image": "https://static.wanted.co.kr/images/tags/bdb973d8-43f7-11e6-945a-0a30d591bfc5.jpg", "title": "기술영업", "counts": { "job": 175, "externalJob": 49833 }, "tagName": "technical sales specialist" },
        { "id": 1035, "image": "https://static.wanted.co.kr/images/tags/6772b2ae.jpg", "title": "솔루션 컨설턴트", "counts": { "job": 107, "externalJob": 67261 }, "tagName": "solutions consultant" },
        { "id": 955, "image": "https://static.wanted.co.kr/images/tags/eaff77cc-ccbc-11e6-84e1-0a30d591bfc5.jpg", "title": "해외영업", "counts": { "job": 69, "externalJob": 73273 }, "tagName": "international sales mgr." },
        { "id": 1037, "image": "https://static.wanted.co.kr/images/tags/021d8d7e.jpg", "title": "고객성공매니저", "counts": { "job": 64, "externalJob": 12106 }, "tagName": "customer success manager" },
        { "id": 1633, "image": "https://static.wanted.co.kr/images/tags/efbb3cce.jpg", "title": "미디어 세일즈", "counts": { "job": 45, "externalJob": 9112 }, "tagName": "media sales manager" },
        { "id": 767, "image": "https://static.wanted.co.kr/images/tags/a547e99a-03a7-11e7-a81b-0aba6235ef6f.jpg", "title": "내부영업", "counts": { "job": 23, "externalJob": 1593 }, "tagName": "inside sales specialist" },
        { "id": 773, "image": "https://static.wanted.co.kr/images/tags/c25e9a12-43f7-11e6-90dd-0a30d591bfc5.jpg", "title": "세일즈 엔지니어", "counts": { "job": 23, "externalJob": 46652 }, "tagName": "sales engineer" },
        { "id": 772, "image": "https://static.wanted.co.kr/images/tags/b0a2ba68.jpg", "title": "의료기기 영업", "counts": { "job": 16, "externalJob": 20044 }, "tagName": "medical device sales specialist" },
        { "id": 771, "image": "https://static.wanted.co.kr/images/tags/55d45eec-03a8-11e7-9be6-0219382c3fab.jpg", "title": "제약영업", "counts": { "job": 9, "externalJob": 77493 }, "tagName": "pharmaceutical sales specialist" }],
      "title": "영업", "counts": { "job": 658, "externalJob": 0 }, "tagName": "sales"
    },
    {
      "id": 517, "image": "https://static.wanted.co.kr/images/tags/6e0effd8.jpg",
      "tags": [
        { "id": 643, "image": "https://static.wanted.co.kr/images/tags/312da9a6-43f8-11e6-90dd-0a30d591bfc5.jpg", "title": "인사담당", "counts": { "job": 259, "externalJob": 79355 }, "tagName": "hr manager" },
        { "id": 644, "image": "https://static.wanted.co.kr/images/tags/4f297912-43f8-11e6-90dd-0a30d591bfc5.jpg", "title": "리크루터", "counts": { "job": 218, "externalJob": 51298 }, "tagName": "recruiter" },
        { "id": 649, "image": "https://static.wanted.co.kr/images/tags/a4958ae0-4fcd-11e6-852d-0a30d591bfc5.jpg", "title": "조직문화", "counts": { "job": 115, "externalJob": 85160 }, "tagName": "organization management" },
        { "id": 645, "image": "https://static.wanted.co.kr/images/tags/74384016-637f-11e6-831d-0a30d591bfc5.png", "title": "평가·보상", "counts": { "job": 112, "externalJob": 73056 }, "tagName": "performance evaluation" },
        { "id": 1041, "image": "https://static.wanted.co.kr/images/tags/97c67da8.jpg", "title": "헤드헌터", "counts": { "job": 60, "externalJob": 4179 }, "tagName": "headhunter" },
        { "id": 650, "image": "https://static.wanted.co.kr/images/tags/7f4f55d8.jpg", "title": "급여담당", "counts": { "job": 53, "externalJob": 170711 }, "tagName": "salary, compensation" },
        { "id": 648, "image": "https://static.wanted.co.kr/images/tags/17088366-43f8-11e6-945a-0a30d591bfc5.jpg", "title": "HRD", "counts": { "job": 49, "externalJob": 45269 }, "tagName": "hr development, training" },
        { "id": 1043, "image": "https://static.wanted.co.kr/images/tags/9be27680.jpg", "title": "HRBP", "counts": { "job": 40, "externalJob": 4532 }, "tagName": "hr business partner" },
        { "id": 647, "image": "https://static.wanted.co.kr/images/tags/b88414f6.jpg", "title": "노무·노사", "counts": { "job": 34, "externalJob": 79750 }, "tagName": "labor and management" },
        { "id": 642, "image": "https://static.wanted.co.kr/images/tags/58a1d2e4-4283-11e6-a15c-029e8c03f357.jpg", "title": "HR 컨설턴트", "counts": { "job": 21, "externalJob": 8269 }, "tagName": "hr consultant" },
        { "id": 1044, "image": "https://static.wanted.co.kr/images/tags/ef352cc4.jpg", "title": "사내 강사", "counts": { "job": 5, "externalJob": 77488 }, "tagName": "lecturer" },
        { "id": 611, "image": "https://static.wanted.co.kr/images/tags/b720a1d8.jpg", "title": "기술 교육", "counts": { "job": 1, "externalJob": 81467 }, "tagName": "technology educator" },
        { "id": 608, "image": "https://static.wanted.co.kr/images/tags/7c803674.jpg", "title": "교사", "counts": { "job": 0, "externalJob": 35459 }, "tagName": "teacher" },
        { "id": 651, "image": "https://static.wanted.co.kr/images/tags/36b3ba26-4283-11e6-a15c-029e8c03f357.jpg", "title": "E-러닝", "counts": { "job": 0, "externalJob": 55771 }, "tagName": "e-learning" },
        { "id": 1042, "image": "https://static.wanted.co.kr/images/tags/afbeded2.jpg", "title": "교수", "counts": { "job": 0, "externalJob": 8634 }, "tagName": "professor" }],
      "title": "인사", "counts": { "job": 424, "externalJob": 0 }, "tagName": "hr"
    },
    {
      "id": 524, "image": "https://static.wanted.co.kr/images/tags/43a5dd52.jpg",
      "tags": [
        { "id": 1046, "image": "https://static.wanted.co.kr/images/tags/7f4f5bcc.jpg", "title": "콘텐츠 크리에이터", "counts": { "job": 185, "externalJob": 4521 }, "tagName": "content creator" },
        { "id": 727, "image": "https://static.wanted.co.kr/images/tags/35754d1c-43f7-11e6-90dd-0a30d591bfc5.jpg", "title": "PD", "counts": { "job": 152, "externalJob": 28250 }, "tagName": "producer" },
        { "id": 723, "image": "https://static.wanted.co.kr/images/tags/93a36738-43e9-11e6-90dd-0a30d591bfc5.jpg", "title": "영상 편집가", "counts": { "job": 124, "externalJob": 13176 }, "tagName": "video editing specialist" },
        { "id": 725, "image": "https://static.wanted.co.kr/images/tags/1a223b92-43f7-11e6-90dd-0a30d591bfc5.jpg", "title": "에디터", "counts": { "job": 96, "externalJob": 12726 }, "tagName": "editor" },
        { "id": 3351, "image": null, "title": "비디오 제작", "counts": { "job": 70, "externalJob": 6871 }, "tagName": "video production" },
        { "id": 724, "image": "https://static.wanted.co.kr/images/tags/2d8d4388-4709-11e6-96e3-0a30d591bfc5.jpg", "title": "작가", "counts": { "job": 45, "externalJob": 9299 }, "tagName": "writer" },
        { "id": 940, "image": "https://static.wanted.co.kr/images/tags/6319a2d8.jpg", "title": "통·번역", "counts": { "job": 28, "externalJob": 4120 }, "tagName": "translator" },
        { "id": 956, "image": "https://static.wanted.co.kr/images/tags/f2bacafc-ccbc-11e6-b4e9-0a30d591bfc5.jpg", "title": "출판 기획자", "counts": { "job": 17, "externalJob": 9155 }, "tagName": "book publisher" },
        { "id": 957, "image": "https://static.wanted.co.kr/images/tags/f9036db0-ccbc-11e6-af0f-0a30d591bfc5.jpg", "title": "음향 엔지니어", "counts": { "job": 14, "externalJob": 19794 }, "tagName": "sound engineer" },
        { "id": 1636, "image": "https://static.wanted.co.kr/images/tags/db453c18.jpg", "title": "라이센스 관리자", "counts": { "job": 13, "externalJob": 6265 }, "tagName": "licence manager" },
        { "id": 729, "image": "https://static.wanted.co.kr/images/tags/35585180-03a0-11e7-8ad5-0219382c3fab.jpg", "title": "사진작가", "counts": { "job": 12, "externalJob": 1422 }, "tagName": "photographer" },
        { "id": 1045, "image": "https://static.wanted.co.kr/images/tags/11b382dc.jpg", "title": "큐레이터", "counts": { "job": 11, "externalJob": 752 }, "tagName": "curator" },
        { "id": 726, "image": "https://static.wanted.co.kr/images/tags/49662d0a-03a0-11e7-bd2d-0aba6235ef6f.jpg", "title": "저널리스트", "counts": { "job": 4, "externalJob": 1040 }, "tagName": "journalist" },
        { "id": 728, "image": "https://static.wanted.co.kr/images/tags/070cda72.jpg", "title": "리포터", "counts": { "job": 2, "externalJob": 12365 }, "tagName": "reporter" }],
      "title": "미디어", "counts": { "job": 334, "externalJob": 0 }, "tagName": "media and communication"
    },
    {
      "id": 959, "image": "https://static.wanted.co.kr/images/tags/2eb98862.jpg",
      "tags": [
        { "id": 892, "image": "https://static.wanted.co.kr/images/tags/151d88cc-43f7-11e6-90dd-0a30d591bfc5.jpg", "title": "게임 기획자", "counts": { "job": 84, "externalJob": 8788 }, "tagName": "game planner" },
        { "id": 880, "image": "https://static.wanted.co.kr/images/tags/710b4bd2-43e9-11e6-945a-0a30d591bfc5.jpg", "title": "게임 그래픽 디자이너", "counts": { "job": 72, "externalJob": 4386 }, "tagName": "game graphic designer" },
        { "id": 961, "image": "https://static.wanted.co.kr/images/tags/bf719a06-cce2-11e6-8d76-0a30d591bfc5.jpg", "title": "게임 클라이언트 개발자", "counts": { "job": 64, "externalJob": 6848 }, "tagName": "game client developer" },
        { "id": 962, "image": "https://static.wanted.co.kr/images/tags/c7812702-cce2-11e6-bef4-0a30d591bfc5.jpg", "title": "모바일 게임 개발자", "counts": { "job": 60, "externalJob": 9661 }, "tagName": "mobile game developer" },
        { "id": 881, "image": "https://static.wanted.co.kr/images/tags/766c06ca-43e9-11e6-945a-0a30d591bfc5.jpg", "title": "게임 아티스트", "counts": { "job": 58, "externalJob": 2730 }, "tagName": "game artist" },
        { "id": 878, "image": "https://static.wanted.co.kr/images/tags/6e370016-43fa-11e6-945a-0a30d591bfc5.jpg", "title": "유니티 개발자", "counts": { "job": 45, "externalJob": 3866 }, "tagName": "unity developer" },
        { "id": 960, "image": "https://static.wanted.co.kr/images/tags/3e2a03e8-ccc4-11e6-95de-0a30d591bfc5.jpg", "title": "게임 서버 개발자", "counts": { "job": 37, "externalJob": 10452 }, "tagName": "game server developer" },
        { "id": 897, "image": "https://static.wanted.co.kr/images/tags/c35f04bc-43fa-11e6-945a-0a30d591bfc5.jpg", "title": "언리얼 개발자", "counts": { "job": 12, "externalJob": 950 }, "tagName": "unreal developer" },
        { "id": 958, "image": "https://static.wanted.co.kr/images/tags/02aa97b2-ccbd-11e6-84e1-0a30d591bfc5.jpg", "title": "게임운영자(GM)", "counts": { "job": 10, "externalJob": 804 }, "tagName": "game master" }],
      "title": "게임 제작", "counts": { "job": 270, "externalJob": 0 }, "tagName": "game production"
    },
    {
      "id": 508, "image": "https://static.wanted.co.kr/images/tags/9f8f0364.jpg",
      "tags": [
        { "id": 1048, "image": "https://static.wanted.co.kr/images/tags/3df6ce34.jpg", "title": "재무 담당자", "counts": { "job": 80, "externalJob": 81996 }, "tagName": "finance manager" },
        { "id": 534, "image": "https://static.wanted.co.kr/images/tags/87875206-0253-11e7-a97f-0213e6175ee7.jpg", "title": "회계담당", "counts": { "job": 76, "externalJob": 29401 }, "tagName": "accountant, treasurer" },
        { "id": 10056, "image": "https://static.wanted.co.kr/images/tags/a8794f7c.jpg", "title": "투자·증권", "counts": { "job": 47, "externalJob": 21358 }, "tagName": "investment, stock manager" },
        { "id": 920, "image": "https://static.wanted.co.kr/images/tags/498615c6-4fcc-11e6-852d-0a30d591bfc5.jpg", "title": "IR", "counts": { "job": 46, "externalJob": 15074 }, "tagName": "ir" },
        { "id": 538, "image": "https://static.wanted.co.kr/images/tags/8b164b12-43f8-11e6-b947-0a30d591bfc5.jpg", "title": "재무 분석가", "counts": { "job": 29, "externalJob": 18639 }, "tagName": "financial analyst" },
        { "id": 547, "image": "https://static.wanted.co.kr/images/tags/f03871ee.jpg", "title": "내부통제 담당자", "counts": { "job": 18, "externalJob": 11546 }, "tagName": "auditor" },
        { "id": 882, "image": "https://static.wanted.co.kr/images/tags/30d52d3a-43e4-11e6-90dd-0a30d591bfc5.jpg", "title": "애널리스트", "counts": { "job": 18, "externalJob": 28942 }, "tagName": "analyst" },
        { "id": 542, "image": "https://static.wanted.co.kr/images/tags/f03d9ae4-4282-11e6-adae-029e8c03f357.jpg", "title": "공인회계사", "counts": { "job": 17, "externalJob": 6920 }, "tagName": "cpa" },
        { "id": 934, "image": "https://static.wanted.co.kr/images/tags/909e107c.jpg", "title": "금융공학자", "counts": { "job": 12, "externalJob": 5308 }, "tagName": "financial engineer" },
        { "id": 936, "image": "https://static.wanted.co.kr/images/tags/29c5a7c0-03ad-11e7-8d2c-0213e6175ee7.jpg", "title": "자산운용가", "counts": { "job": 12, "externalJob": 12246 }, "tagName": "asset manager" },
        { "id": 935, "image": "https://static.wanted.co.kr/images/tags/eba51e1c.jpg", "title": "자산관리사", "counts": { "job": 11, "externalJob": 5201 }, "tagName": "financial advisor" },
        { "id": 938, "image": "https://static.wanted.co.kr/images/tags/3c10b1a4-03ad-11e7-a97f-0213e6175ee7.jpg", "title": "준법감시인", "counts": { "job": 9, "externalJob": 22698 }, "tagName": "compliance manager" },
        { "id": 1047, "image": "https://static.wanted.co.kr/images/tags/eef21f82.jpg", "title": "세무사", "counts": { "job": 9, "externalJob": 36639 }, "tagName": "tax accountant" },
        { "id": 742, "image": "https://static.wanted.co.kr/images/tags/e437590e.jpg", "title": "부동산 자산 관리자", "counts": { "job": 6, "externalJob": 37248 }, "tagName": "property manager" },
        { "id": 933, "image": "https://static.wanted.co.kr/images/tags/6d34b3ca.jpg", "title": "트레이더", "counts": { "job": 5, "externalJob": 4510 }, "tagName": "trader" },
        { "id": 937, "image": "https://static.wanted.co.kr/images/tags/368e3dbe-03ad-11e7-8de0-0213e6175ee7.jpg", "title": "투자은행가", "counts": { "job": 5, "externalJob": 7247 }, "tagName": "investment banker" },
        { "id": 743, "image": "https://static.wanted.co.kr/images/tags/7977af20.jpg", "title": "부동산 중개사", "counts": { "job": 3, "externalJob": 51643 }, "tagName": "realtor" },
        { "id": 684, "image": "https://static.wanted.co.kr/images/tags/6199a4be.jpg", "title": "언더라이터", "counts": { "job": 2, "externalJob": 970 }, "tagName": "underwriter" },
        { "id": 745, "image": "https://static.wanted.co.kr/images/tags/4732fcd6.jpg", "title": "감정평가사", "counts": { "job": 2, "externalJob": 3410 }, "tagName": "appraiser" },
        { "id": 681, "image": "https://static.wanted.co.kr/images/tags/fe711756.jpg", "title": "보험 에이전트", "counts": { "job": 1, "externalJob": 81999 }, "tagName": "insurance agent" },
        { "id": 682, "image": "https://static.wanted.co.kr/images/tags/58383642.jpg", "title": "손해 사정관", "counts": { "job": 0, "externalJob": 56443 }, "tagName": "damage appraiser" },
        { "id": 683, "image": "https://static.wanted.co.kr/images/tags/d1ad9884.jpg", "title": "계리사", "counts": { "job": 0, "externalJob": 879 }, "tagName": "actuary" },
        { "id": 1049, "image": "https://static.wanted.co.kr/images/tags/8f3c656a.jpg", "title": "청구 담당자", "counts": { "job": 0, "externalJob": 39805 }, "tagName": "claims manager" }],
      "title": "금융", "counts": { "job": 190, "externalJob": 0 }, "tagName": "finance"
    },
    {
      "id": 513, "image": "https://static.wanted.co.kr/images/tags/87d8057c.jpg",
      "tags": [
        { "id": 843, "image": null, "title": "기계 엔지니어", "counts": { "job": 33, "externalJob": 56568 }, "tagName": "mechanical engineer" },
        { "id": 823, "image": "https://static.wanted.co.kr/images/tags/162c5f6a-03ad-11e7-a97f-0213e6175ee7.jpg", "title": "전자 엔지니어", "counts": { "job": 30, "externalJob": 51097 }, "tagName": "electronics engineer" },
        { "id": 821, "image": "https://static.wanted.co.kr/images/tags/ecfdcad4.jpg", "title": "전기 엔지니어", "counts": { "job": 23, "externalJob": 54461 }, "tagName": "electrical engineer" },
        { "id": 856, "image": "https://static.wanted.co.kr/images/tags/1ce5a226-03ad-11e7-a97f-0213e6175ee7.jpg", "title": "제품 엔지니어", "counts": { "job": 22, "externalJob": 64975 }, "tagName": "product engineer" },
        { "id": 10145, "image": "https://static.wanted.co.kr/images/tags/e24b9ec5.jpg", "title": "로봇·자동화", "counts": { "job": 20, "externalJob": 721 }, "tagName": "robot·ai" },
        { "id": 10132, "image": "https://static.wanted.co.kr/images/tags/564719af.jpg", "title": "CAD·3D 설계자", "counts": { "job": 19, "externalJob": 223 }, "tagName": "cad·3d engineer" },
        { "id": 859, "image": "https://static.wanted.co.kr/images/tags/bc112a6e-4283-11e6-a15c-029e8c03f357.jpg", "title": "QA 엔지니어", "counts": { "job": 13, "externalJob": 8621 }, "tagName": "qa engineer" },
        { "id": 822, "image": "https://static.wanted.co.kr/images/tags/bf8529d0.jpg", "title": "전기기계 공학자", "counts": { "job": 12, "externalJob": 5201 }, "tagName": "electro mechanical engineer" },
        { "id": 817, "image": "https://static.wanted.co.kr/images/tags/f19c4a7a.jpg", "title": "제어 엔지니어", "counts": { "job": 9, "externalJob": 44704 }, "tagName": "control engineer" },
        { "id": 826, "image": "https://static.wanted.co.kr/images/tags/dbfe5c62.jpg", "title": "장비 엔지니어", "counts": { "job": 8, "externalJob": 45730 }, "tagName": "equipment engineer" },
        { "id": 802, "image": "https://static.wanted.co.kr/images/tags/8ca5981e.jpg", "title": "항공우주 공학자", "counts": { "job": 5, "externalJob": 497 }, "tagName": "aerospace engineer" },
        { "id": 804, "image": "https://static.wanted.co.kr/images/tags/e7843d4a.jpg", "title": "자동차 공학자", "counts": { "job": 5, "externalJob": 4593 }, "tagName": "automotive engineer" },
        { "id": 809, "image": "https://static.wanted.co.kr/images/tags/b55787ea.jpg", "title": "화학공학 엔지니어", "counts": { "job": 5, "externalJob": 6413 }, "tagName": "chemical engineer" },
        { "id": 810, "image": "https://static.wanted.co.kr/images/tags/18d3f01a.jpg", "title": "도면 담당자", "counts": { "job": 5, "externalJob": 56519 }, "tagName": "drafter" },
        { "id": 815, "image": "https://static.wanted.co.kr/images/tags/0e856cfc-03ad-11e7-8de0-0213e6175ee7.jpg", "title": "건설 엔지니어", "counts": { "job": 4, "externalJob": 30609 }, "tagName": "construction engineer" },
        { "id": 819, "image": "https://static.wanted.co.kr/images/tags/15245b62.jpg", "title": "도면 작성가", "counts": { "job": 4, "externalJob": 75 }, "tagName": "floor plan creator" },
        { "id": 811, "image": "https://static.wanted.co.kr/images/tags/dfb9d85c.jpg", "title": "토목기사", "counts": { "job": 3, "externalJob": 21557 }, "tagName": "civil engineer" },
        { "id": 828, "image": "https://static.wanted.co.kr/images/tags/e0d1d1e4.jpg", "title": "설비 엔지니어", "counts": { "job": 3, "externalJob": 48305 }, "tagName": "equipment engineer" },
        { "id": 830, "image": "https://static.wanted.co.kr/images/tags/e855c16c.jpg", "title": "소방안전 기술자", "counts": { "job": 3, "externalJob": 12257 }, "tagName": "fire protection engineer" },
        { "id": 839, "image": null, "title": "인허가 담당 엔지니어", "counts": { "job": 3, "externalJob": 1066 }, "tagName": "licensing engineer" },
        { "id": 860, "image": null, "title": "QC 엔지니어", "counts": { "job": 3, "externalJob": 3254 }, "tagName": "qc engineer" },
        { "id": 824, "image": "https://static.wanted.co.kr/images/tags/a7003e62.jpg", "title": "환경 엔지니어", "counts": { "job": 2, "externalJob": 76546 }, "tagName": "environmental engineer" },
        { "id": 825, "image": "https://static.wanted.co.kr/images/tags/b9e3ed26.jpg", "title": "환경 안전기사", "counts": { "job": 2, "externalJob": 7946 }, "tagName": "environmental safety engineer" },
        { "id": 831, "image": "https://static.wanted.co.kr/images/tags/2c0d268e.jpg", "title": "지리정보시스템", "counts": { "job": 2, "externalJob": 173 }, "tagName": "geographic information systems specialist" },
        { "id": 836, "image": null, "title": "산업 엔지니어", "counts": { "job": 2, "externalJob": 36141 }, "tagName": "industrial engineer" },
        { "id": 842, "image": null, "title": "재료공학자", "counts": { "job": 2, "externalJob": 10403 }, "tagName": "materials engineer" },
        { "id": 847, "image": null, "title": "선박 공학자", "counts": { "job": 2, "externalJob": 3500 }, "tagName": "marine engineer" },
        { "id": 854, "image": null, "title": "플라스틱 엔지니어", "counts": { "job": 2, "externalJob": 3212 }, "tagName": "plastic engineer" },
        { "id": 857, "image": "https://static.wanted.co.kr/images/tags/3b89119a-03ad-11e7-a81b-0aba6235ef6f.jpg", "title": "프로젝트 엔지니어", "counts": { "job": 2, "externalJob": 86385 }, "tagName": "project engineer" },
        { "id": 864, "image": null, "title": "RF 엔지니어", "counts": { "job": 2, "externalJob": 1014 }, "tagName": "rt engineer" },
        { "id": 867, "image": null, "title": "구조공학 엔지니어", "counts": { "job": 2, "externalJob": 5940 }, "tagName": "structural engineer" },
        { "id": 834, "image": null, "title": "보건안전 엔지니어", "counts": { "job": 1, "externalJob": 6192 }, "tagName": "health and safety engineer" },
        { "id": 838, "image": "https://static.wanted.co.kr/images/tags/75370c4e-4283-11e6-adae-029e8c03f357.jpg", "title": "I\u0026C 엔지니어", "counts": { "job": 1, "externalJob": 1605 }, "tagName": "i and c engineer" },
        { "id": 852, "image": null, "title": "배관설계 엔지니어", "counts": { "job": 1, "externalJob": 9148 }, "tagName": "pipe design engineer" },
        { "id": 855, "image": null, "title": "공정 엔지니어", "counts": { "job": 1, "externalJob": 42676 }, "tagName": "process engineer" },
        { "id": 858, "image": null, "title": "사업수주 엔지니어", "counts": { "job": 1, "externalJob": 21730 }, "tagName": "contracts engineer" },
        { "id": 861, "image": null, "title": "전자계전 엔지니어", "counts": { "job": 1, "externalJob": 82 }, "tagName": "electronic relay engineer" },
        { "id": 803, "image": "https://static.wanted.co.kr/images/tags/cfd5ca3c.jpg", "title": "농업 공학자", "counts": { "job": 0, "externalJob": 411 }, "tagName": "agricultural engineer" },
        { "id": 805, "image": null, "title": "유전 공학자", "counts": { "job": 0, "externalJob": 176 }, "tagName": "geneticist" },
        { "id": 806, "image": "https://static.wanted.co.kr/images/tags/ba3e599e.jpg", "title": "생물의학자", "counts": { "job": 0, "externalJob": 794 }, "tagName": "biological scientist" },
        { "id": 807, "image": "https://static.wanted.co.kr/images/tags/e22ed7d6.jpg", "title": "보일러 엔지니어", "counts": { "job": 0, "externalJob": 3239 }, "tagName": "boiler engineer" },
        { "id": 808, "image": "https://static.wanted.co.kr/images/tags/458f3018.jpg", "title": "세라믹 엔지니어", "counts": { "job": 0, "externalJob": 1774 }, "tagName": "ceramic engineer" },
        { "id": 812, "image": "https://static.wanted.co.kr/images/tags/54d88952.jpg", "title": "시운전 엔지니어", "counts": { "job": 0, "externalJob": 16806 }, "tagName": "test and trials engineer" },
        { "id": 820, "image": "https://static.wanted.co.kr/images/tags/76b1c7be.jpg", "title": "시추 엔지니어", "counts": { "job": 0, "externalJob": 538 }, "tagName": "drilling engineer" },
        { "id": 832, "image": "https://static.wanted.co.kr/images/tags/4c2479b8.jpg", "title": "지리학자", "counts": { "job": 0, "externalJob": 25 }, "tagName": "geographer" },
        { "id": 833, "image": "https://static.wanted.co.kr/images/tags/227883f2.jpg", "title": "지질공학자", "counts": { "job": 0, "externalJob": 163 }, "tagName": "geological engineer" },
        { "id": 835, "image": null, "title": "고압설계 엔지니어", "counts": { "job": 0, "externalJob": 1430 }, "tagName": "high voltage design engineer" },
        { "id": 840, "image": null, "title": "생산공학 엔지니어", "counts": { "job": 0, "externalJob": 40970 }, "tagName": "production engineer" },
        { "id": 841, "image": null, "title": "해양공학자", "counts": { "job": 0, "externalJob": 3165 }, "tagName": "marine engineer" },
        { "id": 844, "image": null, "title": "금속 공학자", "counts": { "job": 0, "externalJob": 3307 }, "tagName": "metal engineer" },
        { "id": 845, "image": null, "title": "광산 기술자", "counts": { "job": 0, "externalJob": 462 }, "tagName": "mine engineer" },
        { "id": 846, "image": null, "title": "광산 안전 기술자", "counts": { "job": 0, "externalJob": 348 }, "tagName": "mine safety engineer" },
        { "id": 848, "image": null, "title": "원자력·에너지", "counts": { "job": 0, "externalJob": 2980 }, "tagName": "nuclear engineer" },
        { "id": 850, "image": null, "title": "석유공학 엔지니어", "counts": { "job": 0, "externalJob": 717 }, "tagName": "petroleum engineer" },
        { "id": 853, "image": null, "title": "플랜트 엔지니어", "counts": { "job": 0, "externalJob": 20284 }, "tagName": "plant engineer" },
        { "id": 863, "image": null, "title": "저수처리 엔지니어", "counts": { "job": 0, "externalJob": 5319 }, "tagName": "water treatment process engineer" },
        { "id": 865, "image": null, "title": "회전기계 엔지니어", "counts": { "job": 0, "externalJob": 1162 }, "tagName": "rotary machine engineer" },
        { "id": 869, "image": null, "title": "터빈공학자", "counts": { "job": 0, "externalJob": 284 }, "tagName": "turbine engineer" }],
      "title": "엔지니어링·설계", "counts": { "job": 117, "externalJob": 0 }, "tagName": "engineering"
    },
    {
      "id": 532, "image": "https://static.wanted.co.kr/images/tags/ac0cf75e.jpg", "tags": [
        { "id": 783, "image": "https://static.wanted.co.kr/images/tags/2a28a288-4fc8-11e6-8a12-0a30d591bfc5.jpg", "title": "물류담당", "counts": { "job": 86, "externalJob": 56208 }, "tagName": "logistics manager" },
        { "id": 10148, "image": "https://static.wanted.co.kr/images/tags/0ed51b6e.jpg", "title": "입·출고 관리자", "counts": { "job": 49, "externalJob": 125 }, "tagName": "import or export specialist" },
        { "id": 782, "image": "https://static.wanted.co.kr/images/tags/678d348c-03a9-11e7-b0b5-0219382c3fab.jpg", "title": "물류 분석가", "counts": { "job": 47, "externalJob": 1812 }, "tagName": "logistics analyst" },
        { "id": 10149, "image": "https://static.wanted.co.kr/images/tags/c9cdfa6d.jpg", "title": "유통 관리자", "counts": { "job": 36, "externalJob": 1272 }, "tagName": "distribution manager" },
        { "id": 10151, "image": "https://static.wanted.co.kr/images/tags/a965098b.jpg", "title": "수출입사무", "counts": { "job": 18, "externalJob": 769 }, "tagName": "logistics coordinator" },
        { "id": 777, "image": "https://static.wanted.co.kr/images/tags/0e89ba22-ccbd-11e6-95de-0a30d591bfc5.jpg", "title": "배송담당", "counts": { "job": 11, "externalJob": 73593 }, "tagName": "shipping, receiving clerk" },
        { "id": 786, "image": "https://static.wanted.co.kr/images/tags/f3470398.jpg", "title": "운송 관리자", "counts": { "job": 9, "externalJob": 14465 }, "tagName": "transportation manager" },
        { "id": 10053, "image": "https://static.wanted.co.kr/images/tags/0de100ea.jpg", "title": "무역사무", "counts": { "job": 7, "externalJob": 17859 }, "tagName": "trade administration" },
        { "id": 779, "image": null, "title": "운행 관리원", "counts": { "job": 3, "externalJob": 3543 }, "tagName": "dispatcher" },
        { "id": 780, "image": "https://static.wanted.co.kr/images/tags/4380b0d8.jpg", "title": "지게차 운전사", "counts": { "job": 3, "externalJob": 6748 }, "tagName": "forklift driver" },
        { "id": 787, "image": "https://static.wanted.co.kr/images/tags/0eefc224.jpg", "title": "웨어하우스", "counts": { "job": 3, "externalJob": 1128 }, "tagName": "warehouse specialist" },
        { "id": 781, "image": "https://static.wanted.co.kr/images/tags/77b5ced2.jpg", "title": "운전기사", "counts": { "job": 2, "externalJob": 32660 }, "tagName": "driver" },
        { "id": 785, "image": "https://static.wanted.co.kr/images/tags/03b6efa0.jpg", "title": "선적,발송 사무원", "counts": { "job": 2, "externalJob": 11743 }, "tagName": "shipment, mailing clerk" },
        { "id": 789, "image": "https://static.wanted.co.kr/images/tags/cbc4e8d8.jpg", "title": "해운·해양 운송", "counts": { "job": 2, "externalJob": 5318 }, "tagName": "marine transportation specialist" },
        { "id": 784, "image": "https://static.wanted.co.kr/images/tags/993c311e.jpg", "title": "화물트럭 운전기사", "counts": { "job": 1, "externalJob": 33340 }, "tagName": "cargo truck drivers" },
        { "id": 788, "image": "https://static.wanted.co.kr/images/tags/90409596.jpg", "title": "항공 운송", "counts": { "job": 1, "externalJob": 203 }, "tagName": "air transportation specialist" },
        { "id": 790, "image": "https://static.wanted.co.kr/images/tags/ab782ac6.jpg", "title": "보세사", "counts": { "job": 1, "externalJob": 35 }, "tagName": "bonded transportation specialist" },
        { "id": 10150, "image": "https://static.wanted.co.kr/images/tags/f5d59c36.jpg", "title": "바이어관리·상담·개발", "counts": { "job": 1, "externalJob": 170 }, "tagName": "supply chain manager" },
        { "id": 778, "image": "https://static.wanted.co.kr/images/tags/e0fa996e.jpg", "title": "디젤 정비공", "counts": { "job": 0, "externalJob": 448 }, "tagName": "diesel mechanic" },
        { "id": 10139, "image": "https://static.wanted.co.kr/images/tags/d16c1eb3.jpg", "title": "관세사", "counts": { "job": 0, "externalJob": 146 }, "tagName": "logistics customs officer" },
        { "id": 10140, "image": "https://static.wanted.co.kr/images/tags/361a73d2.jpg", "title": "원산지관리사", "counts": { "job": 0, "externalJob": 203 }, "tagName": "logistics manager" }],
      "title": "물류·무역", "counts": { "job": 113, "externalJob": 0 }, "tagName": "logistics and trade"
    },
    {
      "id": 515, "image": "https://static.wanted.co.kr/images/tags/7952b34e.jpg",
      "tags": [
        { "id": 739, "image": "https://static.wanted.co.kr/images/tags/83c6be50.jpg", "title": "연구원", "counts": { "job": 57, "externalJob": 15846 }, "tagName": "researcher" },
        { "id": 735, "image": "https://static.wanted.co.kr/images/tags/c4e62e6a.jpg", "title": "임상시험 연구원", "counts": { "job": 33, "externalJob": 591 }, "tagName": "clinical trial researcher" },
        { "id": 740, "image": "https://static.wanted.co.kr/images/tags/038d30da.jpg", "title": "생명공학 연구원", "counts": { "job": 31, "externalJob": 1220 }, "tagName": "biotechnology researcher" },
        { "id": 736, "image": "https://static.wanted.co.kr/images/tags/aaa86cac.jpg", "title": "임상시험 간호사", "counts": { "job": 16, "externalJob": 6279 }, "tagName": "clinical trial nurse" },
        { "id": 626, "image": "https://static.wanted.co.kr/images/tags/aba9c04c.jpg", "title": "임상병리사", "counts": { "job": 10, "externalJob": 11766 }, "tagName": "medical technologist" },
        { "id": 627, "image": "https://static.wanted.co.kr/images/tags/376cff36.jpg", "title": "간호사", "counts": { "job": 10, "externalJob": 72946 }, "tagName": "nurse" },
        { "id": 731, "image": "https://static.wanted.co.kr/images/tags/7f83955c.jpg", "title": "약학 분석 화학자", "counts": { "job": 10, "externalJob": 956 }, "tagName": "pharmaceutical analytical chemist" },
        { "id": 733, "image": "https://static.wanted.co.kr/images/tags/905cf828-03a1-11e7-bd2d-0aba6235ef6f.jpg", "title": "약사", "counts": { "job": 6, "externalJob": 56678 }, "tagName": "pharmacist" },
        { "id": 634, "image": "https://static.wanted.co.kr/images/tags/58260bc0.jpg", "title": "수의사", "counts": { "job": 4, "externalJob": 3197 }, "tagName": "veterinarian" },
        { "id": 737, "image": "https://static.wanted.co.kr/images/tags/31f41a02.jpg", "title": "미생물학자", "counts": { "job": 4, "externalJob": 564 }, "tagName": "microbiologist" },
        { "id": 738, "image": null, "title": "유전공학자", "counts": { "job": 4, "externalJob": 191 }, "tagName": "geneticist" },
        { "id": 622, "image": "https://static.wanted.co.kr/images/tags/58f2d248.jpg", "title": "치과 위생사", "counts": { "job": 3, "externalJob": 7465 }, "tagName": "dental hygienist" },
        { "id": 10135, "image": "https://static.wanted.co.kr/images/tags/6dc37980.jpg", "title": "의무기록사", "counts": { "job": 3, "externalJob": 299 }, "tagName": "medical records technician" },
        { "id": 625, "image": "https://static.wanted.co.kr/images/tags/2c06bb78.jpg", "title": "조무사", "counts": { "job": 1, "externalJob": 86778 }, "tagName": "aide" },
        { "id": 632, "image": "https://static.wanted.co.kr/images/tags/4b816338.jpg", "title": "수의 테크니션", "counts": { "job": 1, "externalJob": 108 }, "tagName": "veterinary specialist" },
        { "id": 636, "image": "https://static.wanted.co.kr/images/tags/38c892dc.jpg", "title": "치과의사", "counts": { "job": 1, "externalJob": 13025 }, "tagName": "dentist" },
        { "id": 10054, "image": "https://static.wanted.co.kr/images/tags/499ba946.jpg", "title": "방사선사", "counts": { "job": 1, "externalJob": 7980 }, "tagName": "radiology" },
        { "id": 10147, "image": "https://static.wanted.co.kr/images/tags/921854c4.jpg", "title": "임상심리사", "counts": { "job": 1, "externalJob": 242 }, "tagName": "clinical psychologist" },
        { "id": 623, "image": "https://static.wanted.co.kr/images/tags/36eac8d6.jpg", "title": "증례 관리자", "counts": { "job": 0, "externalJob": 4313 }, "tagName": "case manager" },
        { "id": 624, "image": "https://static.wanted.co.kr/images/tags/46095954.jpg", "title": "간병인", "counts": { "job": 0, "externalJob": 61361 }, "tagName": "caregiver" },
        { "id": 629, "image": "https://static.wanted.co.kr/images/tags/f3e231b4.jpg", "title": "작업 치료사", "counts": { "job": 0, "externalJob": 42022 }, "tagName": "occupational therapist" },
        { "id": 630, "image": "https://static.wanted.co.kr/images/tags/55b9acae.jpg", "title": "물리 치료사", "counts": { "job": 0, "externalJob": 48926 }, "tagName": "physical therapist" },
        { "id": 631, "image": "https://static.wanted.co.kr/images/tags/acddd3c6.jpg", "title": "호흡장애 치료사", "counts": { "job": 0, "externalJob": 45 }, "tagName": "respiratory disorders therapist" },
        { "id": 633, "image": "https://static.wanted.co.kr/images/tags/a1644634.jpg", "title": "의사", "counts": { "job": 0, "externalJob": 26400 }, "tagName": "doctor" },
        { "id": 635, "image": "https://static.wanted.co.kr/images/tags/5d7abe3e.jpg", "title": "간호 조무사", "counts": { "job": 0, "externalJob": 43615 }, "tagName": "nurse's aide" },
        { "id": 637, "image": "https://static.wanted.co.kr/images/tags/4ca10988.jpg", "title": "검안사", "counts": { "job": 0, "externalJob": 597 }, "tagName": "optometrist" },
        { "id": 732, "image": "https://static.wanted.co.kr/images/tags/6e1966ca.jpg", "title": "연구실 기사", "counts": { "job": 0, "externalJob": 2347 }, "tagName": "laboratory technician" },
        { "id": 734, "image": "https://static.wanted.co.kr/images/tags/6c538f64.jpg", "title": "약사 보조원", "counts": { "job": 0, "externalJob": 1030 }, "tagName": "pharmacist assistant" },
        { "id": 1040, "image": "https://static.wanted.co.kr/images/tags/b6f4c4c4.jpg", "title": "한의사", "counts": { "job": 0, "externalJob": 695 }, "tagName": "oriental medical doctor" },
        { "id": 10134, "image": "https://static.wanted.co.kr/images/tags/c8055d89.jpg", "title": "병원 코디네이터", "counts": { "job": 0, "externalJob": 125 }, "tagName": "hospital coordinator" }],
      "title": "의료·제약·바이오", "counts": { "job": 94, "externalJob": 0 }, "tagName": "bio, medical"
    },
    {
      "id": 522, "image": "https://static.wanted.co.kr/images/tags/539a0896.jpg",
      "tags": [
        { "id": 704, "image": "https://static.wanted.co.kr/images/tags/7b021e52.jpg", "title": "품질 관리자", "counts": { "job": 37, "externalJob": 62014 }, "tagName": "quality manager" },
        { "id": 701, "image": "https://static.wanted.co.kr/images/tags/aa5ec0e6-039f-11e7-a97f-0213e6175ee7.jpg", "title": "생산 관리자", "counts": { "job": 29, "externalJob": 80401 }, "tagName": "production manager" },
        { "id": 699, "image": null, "title": "자재관리·구매", "counts": { "job": 23, "externalJob": 22641 }, "tagName": "materials manager" },
        { "id": 10113, "image": "https://static.wanted.co.kr/images/tags/08515c8a.jpg", "title": "섬유·의류·패션", "counts": { "job": 14, "externalJob": 225 }, "tagName": "textile · clothing · fashion" },
        { "id": 703, "image": "https://static.wanted.co.kr/images/tags/b97afe64-039f-11e7-bedb-0213e6175ee7.jpg", "title": "공정 관리자", "counts": { "job": 13, "externalJob": 107604 }, "tagName": "process manager" },
        { "id": 698, "image": "https://static.wanted.co.kr/images/tags/27a85ab4.jpg", "title": "제조 엔지니어", "counts": { "job": 9, "externalJob": 47101 }, "tagName": "manufacturing engineer" },
        { "id": 700, "image": "https://static.wanted.co.kr/images/tags/3ed70ee8-031b-11e7-b0b5-0219382c3fab.jpg", "title": "기계·설비·설계", "counts": { "job": 6, "externalJob": 63100 }, "tagName": "machinery, equipment operation" },
        { "id": 10114, "image": "https://static.wanted.co.kr/images/tags/5a0d0904.jpg", "title": "반도체·디스플레이", "counts": { "job": 4, "externalJob": 362 }, "tagName": "semiconductor · screens" },
        { "id": 696, "image": "https://static.wanted.co.kr/images/tags/3542960a-031a-11e7-a81b-0aba6235ef6f.jpg", "title": "화학자", "counts": { "job": 3, "externalJob": 1579 }, "tagName": "chemist" },
        { "id": 697, "image": "https://static.wanted.co.kr/images/tags/cad900f0-43f8-11e6-aa6b-0a30d591bfc5.jpg", "title": "기계제작 기술자", "counts": { "job": 3, "externalJob": 61051 }, "tagName": "mechanical production technician" },
        { "id": 702, "image": "https://static.wanted.co.kr/images/tags/cc0e419e-039f-11e7-8502-0aba6235ef6f.jpg", "title": "생산직 종사자", "counts": { "job": 3, "externalJob": 37756 }, "tagName": "production worker" },
        { "id": 706, "image": "https://static.wanted.co.kr/images/tags/40e73766.jpg", "title": "제조 테스트 엔지니어", "counts": { "job": 2, "externalJob": 51097 }, "tagName": "test engineer" },
        { "id": 695, "image": "https://static.wanted.co.kr/images/tags/fe7fc226.jpg", "title": "조립 기술자", "counts": { "job": 1, "externalJob": 58333 }, "tagName": "assembly technician" },
        { "id": 705, "image": "https://static.wanted.co.kr/images/tags/57bf5d4e.jpg", "title": "안전 관리자", "counts": { "job": 1, "externalJob": 58834 }, "tagName": "safety manager" }],
      "title": "제조·생산", "counts": { "job": 79, "externalJob": 0 }, "tagName": "manufacturing"
    },
    {
      "id": 521, "image": "https://static.wanted.co.kr/images/tags/601ae856.jpg",
      "tags": [
        { "id": 1002, "image": "https://static.wanted.co.kr/images/tags/68a88b0a.jpg", "title": "법무담당", "counts": { "job": 44, "externalJob": 3275 }, "tagName": "legal representative" },
        { "id": 691, "image": "https://static.wanted.co.kr/images/tags/c6dc9202-0318-11e7-8ad5-0219382c3fab.jpg", "title": "변호사", "counts": { "job": 33, "externalJob": 15239 }, "tagName": "lawyer" },
        { "id": 692, "image": "https://static.wanted.co.kr/images/tags/d840deda-0319-11e7-a894-0aba6235ef6f.jpg", "title": "법무 자문위원", "counts": { "job": 11, "externalJob": 1239 }, "tagName": "general counsel" },
        { "id": 10137, "image": "https://static.wanted.co.kr/images/tags/437b3d12.jpg", "title": "특허담당", "counts": { "job": 9, "externalJob": 525 }, "tagName": "patent administrator" },
        { "id": 10136, "image": "https://static.wanted.co.kr/images/tags/8d32b81a.jpg", "title": "변리사", "counts": { "job": 5, "externalJob": 41 }, "tagName": "patent attorney" },
        { "id": 694, "image": "https://static.wanted.co.kr/images/tags/86a7f94c.jpg", "title": "법무사", "counts": { "job": 1, "externalJob": 9957 }, "tagName": "judicial scrivener" },
        { "id": 686, "image": "https://static.wanted.co.kr/images/tags/400a9d9e.jpg", "title": "수사관", "counts": { "job": 0, "externalJob": 1881 }, "tagName": "investigator" },
        { "id": 687, "image": "https://static.wanted.co.kr/images/tags/dcd26cee.jpg", "title": "보호 관찰관", "counts": { "job": 0, "externalJob": 277 }, "tagName": "probation officer" },
        { "id": 688, "image": "https://static.wanted.co.kr/images/tags/4c372252.jpg", "title": "경찰관", "counts": { "job": 0, "externalJob": 7343 }, "tagName": "police officer" },
        { "id": 689, "image": "https://static.wanted.co.kr/images/tags/b442b838.jpg", "title": "보안요원", "counts": { "job": 0, "externalJob": 75827 }, "tagName": "security guard" },
        { "id": 690, "image": "https://static.wanted.co.kr/images/tags/39ba58f6.jpg", "title": "경호원", "counts": { "job": 0, "externalJob": 3165 }, "tagName": "bodyguard" },
        { "id": 693, "image": "https://static.wanted.co.kr/images/tags/7f32f9e6.jpg", "title": "법무관", "counts": { "job": 0, "externalJob": 1196 }, "tagName": "solicitor" }],
      "title": "법률·법집행기관", "counts": { "job": 62, "externalJob": 0 }, "tagName": "law"
    },
    {
      "id": 10101, "image": "https://static.wanted.co.kr/images/tags/9755eed1.jpg",
      "tags": [
        { "id": 10103, "image": "https://static.wanted.co.kr/images/tags/72f149b2.jpg", "title": "교재·교육기획", "counts": { "job": 52, "externalJob": 297 }, "tagName": "educational publisher" },
        { "id": 10106, "image": "https://static.wanted.co.kr/images/tags/849b212b.jpg", "title": "외국어교육", "counts": { "job": 18, "externalJob": 412 }, "tagName": "foreign language educator" },
        { "id": 10104, "image": "https://static.wanted.co.kr/images/tags/29385c79.jpg", "title": "학원강사", "counts": { "job": 15, "externalJob": 798 }, "tagName": "private tutor" },
        { "id": 10102, "image": "https://static.wanted.co.kr/images/tags/6459b56e.jpg", "title": "전문강사", "counts": { "job": 12, "externalJob": 779 }, "tagName": "educational instructor" },
        { "id": 10109, "image": "https://static.wanted.co.kr/images/tags/e5e34efd.jpg", "title": "자격증·기술전문교육", "counts": { "job": 12, "externalJob": 194 }, "tagName": "certification and technical training" },
        { "id": 10108, "image": "https://static.wanted.co.kr/images/tags/24f5b854.jpg", "title": "초·중·고 교사", "counts": { "job": 4, "externalJob": 87 }, "tagName": "elementary or middle or high school teacher" },
        { "id": 10105, "image": "https://static.wanted.co.kr/images/tags/f7a1dac8.jpg", "title": "교직원", "counts": { "job": 1, "externalJob": 718 }, "tagName": "faculty and staff" },
        { "id": 10107, "image": "https://static.wanted.co.kr/images/tags/55e4ec71.jpg", "title": "유치원·보육교사", "counts": { "job": 0, "externalJob": 362 }, "tagName": "kindergarten and childcare teacher" }],
      "title": "교육", "counts": { "job": 61, "externalJob": 0 }, "tagName": "education"
    },
    {
      "id": 10057, "image": "https://static.wanted.co.kr/images/tags/d4536952.jpg",
      "tags": [
        { "id": 10153, "image": "https://static.wanted.co.kr/images/tags/17a53bd1.jpg", "title": "식품가공·개발", "counts": { "job": 22, "externalJob": 801 }, "tagName": "food processing · development" },
        { "id": 761, "image": "https://static.wanted.co.kr/images/tags/6885cf40-637f-11e6-831d-0a30d591bfc5.jpg", "title": "식품 MD", "counts": { "job": 21, "externalJob": 1767 }, "tagName": "food md" },
        { "id": 749, "image": "https://static.wanted.co.kr/images/tags/a1b328cc.jpg", "title": "외식업 종사자", "counts": { "job": 17, "externalJob": 38206 }, "tagName": "restaurant worker" },
        { "id": 748, "image": "https://static.wanted.co.kr/images/tags/7f9b4a94.jpg", "title": "요리사", "counts": { "job": 12, "externalJob": 32074 }, "tagName": "chef" },
        { "id": 10058, "image": "https://static.wanted.co.kr/images/tags/22ba7996.jpg", "title": "메뉴개발", "counts": { "job": 11, "externalJob": 25318 }, "tagName": "restaurant management" },
        { "id": 750, "image": "https://static.wanted.co.kr/images/tags/e7dd1766.jpg", "title": "레스토랑 관리자", "counts": { "job": 5, "externalJob": 14949 }, "tagName": "restaurant manager" },
        { "id": 747, "image": "https://static.wanted.co.kr/images/tags/36e06782.jpg", "title": "바텐더", "counts": { "job": 4, "externalJob": 5232 }, "tagName": "bartender" },
        { "id": 628, "image": "https://static.wanted.co.kr/images/tags/b052888c.jpg", "title": "영양사", "counts": { "job": 1, "externalJob": 3613 }, "tagName": "nutritionist" },
        { "id": 10152, "image": "https://static.wanted.co.kr/images/tags/427e3e4e.jpg", "title": "소믈리에", "counts": { "job": 1, "externalJob": 168 }, "tagName": "sommelier" },
        { "id": 10154, "image": "https://static.wanted.co.kr/images/tags/0b479ede.jpg", "title": "바리스타", "counts": { "job": 1, "externalJob": 327 }, "tagName": "barista" },
        { "id": 746, "image": "https://static.wanted.co.kr/images/tags/dbf2bd76.jpg", "title": "제과·제빵사", "counts": { "job": 0, "externalJob": 6988 }, "tagName": "baker" },
        { "id": 10141, "image": "https://static.wanted.co.kr/images/tags/a2f54b2e.jpg", "title": "푸드스타일리스트", "counts": { "job": 0, "externalJob": 40 }, "tagName": "food stylist" }],
      "title": "식·음료", "counts": { "job": 49, "externalJob": 0 }, "tagName": "f and b"
    },
    {
      "id": 509, "image": "https://static.wanted.co.kr/images/tags/974967d0.jpg",
      "tags": [
        { "id": 10143, "image": "https://static.wanted.co.kr/images/tags/52b43ffc.jpg", "title": "건축시공·감리", "counts": { "job": 20, "externalJob": 1276 }, "tagName": "construction manager" },
        { "id": 10142, "image": "https://static.wanted.co.kr/images/tags/a3529322.jpg", "title": "실내건축", "counts": { "job": 13, "externalJob": 725 }, "tagName": "interior architecture" },
        { "id": 572, "image": "https://static.wanted.co.kr/images/tags/d43af124.jpg", "title": "현장 소장", "counts": { "job": 10, "externalJob": 75492 }, "tagName": "site manager" },
        { "id": 10144, "image": "https://static.wanted.co.kr/images/tags/c2223e20.jpg", "title": "건설 안전·품질·검사", "counts": { "job": 6, "externalJob": 407 }, "tagName": "construction inspector" },
        { "id": 575, "image": "https://static.wanted.co.kr/images/tags/6fc39f94.jpg", "title": "유지보수 관리자", "counts": { "job": 5, "externalJob": 26565 }, "tagName": "maintenance manager" },
        { "id": 576, "image": "https://static.wanted.co.kr/images/tags/8dae9f1c.jpg", "title": "관리인", "counts": { "job": 4, "externalJob": 128586 }, "tagName": "manager" },
        { "id": 604, "image": "https://static.wanted.co.kr/images/tags/1216fbdc-4284-11e6-a15c-029e8c03f357.jpg", "title": "건축가", "counts": { "job": 4, "externalJob": 82525 }, "tagName": "architect" },
        { "id": 584, "image": "https://static.wanted.co.kr/images/tags/2dfbd79c.jpg", "title": "견적 기술자", "counts": { "job": 3, "externalJob": 17334 }, "tagName": "estimation engineer" },
        { "id": 577, "image": "https://static.wanted.co.kr/images/tags/db158410.jpg", "title": "전기 기술자", "counts": { "job": 2, "externalJob": 62634 }, "tagName": "electrician" },
        { "id": 580, "image": "https://static.wanted.co.kr/images/tags/67ff458c.jpg", "title": "플랜트 관리자", "counts": { "job": 1, "externalJob": 10525 }, "tagName": "plant manager" },
        { "id": 571, "image": "https://static.wanted.co.kr/images/tags/5a12d500.jpg", "title": "목수", "counts": { "job": 0, "externalJob": 91156 }, "tagName": "carpenter" },
        { "id": 573, "image": "https://static.wanted.co.kr/images/tags/1e6be40c.jpg", "title": "중장비 기술자", "counts": { "job": 0, "externalJob": 44733 }, "tagName": "heavy equipment technician" },
        { "id": 574, "image": "https://static.wanted.co.kr/images/tags/ee8c2b02.jpg", "title": "정비공", "counts": { "job": 0, "externalJob": 19757 }, "tagName": "mechanic" },
        { "id": 578, "image": "https://static.wanted.co.kr/images/tags/ca4acd48.jpg", "title": "인스톨러", "counts": { "job": 0, "externalJob": 2338 }, "tagName": "installer" },
        { "id": 579, "image": "https://static.wanted.co.kr/images/tags/76e60f54.jpg", "title": "페인터", "counts": { "job": 0, "externalJob": 757 }, "tagName": "painter" },
        { "id": 581, "image": "https://static.wanted.co.kr/images/tags/aa10a0c6.jpg", "title": "용접기사", "counts": { "job": 0, "externalJob": 24596 }, "tagName": "welder" },
        { "id": 582, "image": "https://static.wanted.co.kr/images/tags/417c01b0.jpg", "title": "배관공", "counts": { "job": 0, "externalJob": 28064 }, "tagName": "plumber" },
        { "id": 583, "image": "https://static.wanted.co.kr/images/tags/ac420272.jpg", "title": "연관공", "counts": { "job": 0, "externalJob": 4215 }, "tagName": "sanitary engineer" },
        { "id": 585, "image": "https://static.wanted.co.kr/images/tags/40ea813c.jpg", "title": "측량·계측", "counts": { "job": 0, "externalJob": 46585 }, "tagName": "surveying engineer" }],
      "title": "건설·시설", "counts": { "job": 30, "externalJob": 0 }, "tagName": "construction"
    },
    {
      "id": 514, "image": "https://static.wanted.co.kr/images/tags/80c36024.jpg",
      "tags": [
        { "id": 609, "image": "https://static.wanted.co.kr/images/tags/3cfade82.jpg", "title": "카운셀러", "counts": { "job": 3, "externalJob": 40814 }, "tagName": "counselor" },
        { "id": 617, "image": "https://static.wanted.co.kr/images/tags/08367fe4.jpg", "title": "정보 분석가", "counts": { "job": 3, "externalJob": 13943 }, "tagName": "information analyst" },
        { "id": 619, "image": "https://static.wanted.co.kr/images/tags/46f9f51c.jpg", "title": "지역 전문가", "counts": { "job": 2, "externalJob": 13533 }, "tagName": "local specialist" },
        { "id": 620, "image": "https://static.wanted.co.kr/images/tags/65d046d0.jpg", "title": "공무원", "counts": { "job": 2, "externalJob": 8348 }, "tagName": "public officer" },
        { "id": 615, "image": "https://static.wanted.co.kr/images/tags/4ab13082.jpg", "title": "소방관", "counts": { "job": 0, "externalJob": 3387 }, "tagName": "firefighter" },
        { "id": 616, "image": "https://static.wanted.co.kr/images/tags/bab21a5c.jpg", "title": "환경 전문가", "counts": { "job": 0, "externalJob": 17827 }, "tagName": "environmental specialist" },
        { "id": 618, "image": "https://static.wanted.co.kr/images/tags/b2d4cc36.jpg", "title": "인명 구조원", "counts": { "job": 0, "externalJob": 603 }, "tagName": "lifeguard" },
        { "id": 621, "image": "https://static.wanted.co.kr/images/tags/2d48a8ca.jpg", "title": "직업군인", "counts": { "job": 0, "externalJob": 14877 }, "tagName": "professional soldier" },
        { "id": 730, "image": "https://static.wanted.co.kr/images/tags/d3993fa6.jpg", "title": "자원봉사자", "counts": { "job": 0, "externalJob": 36869 }, "tagName": "volunteer" },
        { "id": 10055, "image": "https://static.wanted.co.kr/images/tags/7b9042ea.jpg", "title": "사회복지사", "counts": { "job": 0, "externalJob": 88711 }, "tagName": "social worker" },
        { "id": 10133, "image": "https://static.wanted.co.kr/images/tags/b74d764e.jpg", "title": "응급구조사", "counts": { "job": 0, "externalJob": 44 }, "tagName": "emergency responders (emts)" },
        { "id": 10146, "image": "https://static.wanted.co.kr/images/tags/7e340fee.jpg", "title": "요양보호사", "counts": { "job": 0, "externalJob": 904 }, "tagName": "caretaker" }],
      "title": "공공·복지", "counts": { "job": 4, "externalJob": 0 }, "tagName": "public·social work"
    }
  ]

export default categories;